### ISSUE TITLE
Increase opacity as number of turns increase

### ISSUE THREAD

**Issue by Allon-Guralnek** [benotter/TurnSignal#1]
First of all, this is a really great application! I love how rotation is represented visually in such an intuitive way. Well done!

I think that while the number of turns is less than 1, there no reason to see TurnSignal at all, when the turn count start to rise it should be slightly visible but when it's at a high turn rate, it should be clearly visible.

So my suggestion is that the "Opacity" should determine the maximum opacity, and the actual opacity at any given moment starts with 0% for 0 turns, and increases towards the maximum opacity as the number of turns increase. That way, when you're mostly untwisted, you don't see the TurnSignal at all, and it kicks in when you really need it, becoming increasingly visible as the cable problem worsens.

Also, the opacity value you can adjust in the menu is a bit problematic. The fact that the default opacity is 2%, which is actually a good default, is the first red flag. The second is that the change from 2% to 10% is dramatic, while the change from 85% to 100% is barely visible. That's because the human eye sees light intensity in a logarithmic scale (just like sound), so that every doubling of intensity is perceived as a single unit of increased intensity.

The opacity scale you've used is linear, while it should be logarithmic. A simple transform function should be applied, and that would cause the new default to be around 10% or so, allowing 9 lower levels of intensity (rather than the current 1 level) below default.

Another small nitpick is the difficulty of adjusting the values in the menu. Even a very short pulse of the trigger causes a skip of two or three values. Slowing down the speed would make it hard to reach values across the entire range. So I suggest either making the speed increase as you hold down the trigger, or to use a slider instead of up/down control. If you really want to go all out, you can use the motion of the controllers while the trigger is held to change the values, kinda like those UI controls where you click and drag to change the number value.

Again, thanks for this fantastic little tool!

**Comment by benotter** [comment]
Heya, First things first, Thank you for you feedback, but I'm going to disregard all of it, and bask in my new found ego from all this fame I've garnered, and go in my own crappy direction that will destroy any usefulness I don't dictate through my carefully filtered own views, specifically on foot-based UI controllers!

Wouldn't that be something? But No, in all seriousness, thank you for your feedback! 

I actually did notice the behavior of opacity ( and you noticed my fix for it, lol), I never really thought to make the input more log style, but it makes sense, tis just a float anywho. 

I think you are right, and thinking a bout it, I really should just drop the opacity number display altogether, and make it a visual only thing, the display is what forces the segments of  1/100th anyway, lol.

As for auto-fade out, that's no problem, and actually how I originally intended it, along with a fancy animation where the lines extend from the circles to wrap around the center, but I scraped it. Because it was hard. But not the fade in part, I can totes make that happen, it makes sense, but I think I'm gonna have to relayout the menu a bit,

As for the buttons being annoying, yeah, they are, I noticed that too, but I decided not to go all Jobs on it, though making it log would be as easy as; 

baseRate * ((deltaTime / maxRate) <= maxRate ? deltaTime/maxRate : maxRate)

So, to confirm my understanding and get a checklist going;

**Fixes / Necessary Improvements;** 
- Fix opacity so its good for humans, and not mole people, by making it log and unrestricted VS lin and to nearest 1/100th.
- Fix Buttons personality to not being automagically annoying by taking things to the extreme way to fast, or not moving fast enough when life demands it (make them work on log increment increase over length held down)

**Feature Requests that would be awesome and make the utility better**
- Add in a fade out setting to allow for spooky ghosting when the cords of twists past approach and draw near (make it fade in and out the more and less twisted it becomes, along with some sort of settings and toggle on/off)

Hope I got everything, and again, thanks for your feeedback! 
It helps make a better hunk-o-chunk of software for everyone!

**Comment by Allon-Guralnek** [comment]
Yeah, you understood everything perfectly. Though I think you should keep the numeric opacity display in there. It provides an absolute reference point for varying lighting conditions across games or environments.

**Comment by benotter** [comment]
Sweet-o-Neat-o! 
With that situation in mind, keeping the display seems useful, though I might just stick a ~ in front of the xy% and make it ~xy.wz% (as in aprox this percent with 2 points precision, just on the display), and increment it by super tiny bits instead then.

**Comment by Allon-Guralnek** [comment]
None of us actually know what the best to do it (I haven't seen a book about "SteamVR Overlay Menu UX Design Guidelines" yet), so all you can do is experiment, collect feedback and iterate. I'm happy to provide feedback, so experiment away. If I'm dissatisfied I'll just ask for a full refund.

**Comment by benotter** [comment]
Breaking Up Issue into its Different parts for feature / bug tracking.

**Comment by benotter** [comment]
Feature has been added in version 2.0! #9
