### ISSUE TITLE
Settings not saved

### ISSUE THREAD

**Issue by jacrify** [benotter/TurnSignal#23]
Hi Ben. I use the opacity setting and it isn't saving between sessions. I need to go back in and turn it on every time.

Love your work.

**Comment by benotter** [comment]
Heya, Thanks Man, and thanks for the Report!

I think this is due to the way I prioritize preference files from the local disk, and SteamCloud (Even when its disabled), so I'm going to heavily revise how that's handled.

(Hopefully) Expect 2.3.x to release very soon and remedy this, its top priority atm.

**Comment by benotter** [comment]
Hopefully fixed in the newly released Released 2.3.0!

**Comment by jacrify** [comment]
Tested, confirmed fixed. You rock, three hours from report to live fix.
