### ISSUE TITLE
Turn signal not showing in headset any more

### ISSUE THREAD

**Issue by jacrify** [benotter/TurnSignal#24]
Not sure when this started- a couple of days ago? Shows in desktop window, can't seem to get it to appear in headset.

I really really miss it

**Comment by benotter** [comment]
Hmm, this may be due to some bugs in the update 2.3.0, and how it handles flipping the flower pattern on the controllers, 

If you could try the Reset Settings option at the bottom of the TurnSignal menu, and see if that helps, that would be great!

If the newer build doesn't seem to work at all, I have posted the older builds under the 'Betas' tab in the apps properties on Steam, if all else fails, maybe give that a shot until I can figure out the underlying issues!

Thank you for the feedback and report!

**Comment by jacrify** [comment]
fixed in latest version thanks

**Comment by benotter** [comment]
Oh nice, cool!
Closing the issue!
